# from Dustin's repo https://github.com/dabreegster/talks/tree/main/.github/workflows
name: Deploy slides

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v0.9.4/quarto-0.9.4-linux-amd64.deb
        sudo dpkg -i quarto-0.9.4-linux-amd64.deb

    -name: Install FOntawesome
      run: |
        quarto install extension quarto-ext/fontawesome

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
